### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sctv-hamanaka** [iBicha/WebRTC-for-Unity#4]
Hi,
Is there any specific reason why you choose GPL license? As WebRTC is licensed under three clause BSD license, I prefer the same license as WebRTC itself.

https://webrtc.org/license/

**Comment by iBicha** [comment]
You are absolutely right, I did not pay attention since this project is still at its beginning (Therefore I didn't give it the proper care in terms of licensing)
Will update and close.
